### ISSUE TITLE
spanner::Client deadlocks with about 100 threads

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1000]
Running this function, with the same `spanner::Client` on about 100 threads deadlocks:

```C++
int RunTask(Config const& config, cloud_spanner::Client client,
            RandomKeyGenerator const& key_generator) {
  int count = 0;
  std::string value(1024, 'A');
  for (auto start = std::chrono::steady_clock::now(),
            deadline = start + config.iteration_duration;
       start < deadline; start = std::chrono::steady_clock::now()) {
    auto key = key_generator();
    auto m = cloud_spanner::MakeInsertOrUpdateMutation(
        "KeyValue", {"Key", "Value"}, key, value);
    auto result = client.Commit([&m](cloud_spanner::Transaction const&) {
      return cloud_spanner::Mutations{m};
    });
    ++count;
  }
  return count;
}
```

This may be a problem with the client library code, with gRPC, with the service, or maybe it is not a problem and my code is just broken. In any case, we should investigate before cutting Beta or GA.

**Comment by coryan** [comment]
Also a potential answer is "do not use 100 threads!".

**Comment by devjgm** [comment]
From https://cloud.google.com/spanner/docs/sessions

> "For users working with the RPC API, we recommend having the cache store no more than 100 sessions, because 100 is the maximum number of concurrent sessions per gRPC channel."

**Comment by coryan** [comment]
Yup, that could do it.

**Comment by coryan** [comment]
Closing, the answer is not to use that many threads on a single connection.

**Comment by mr-salty** [comment]
I'm going to reopen this because it shouldn't deadlock regardless - even in the original code, with the session pool we had, I'd have expected all of the threads to eventually make progress.

**Comment by mr-salty** [comment]
I believe I introduced this bug in #925 - the [logic that tries to do `cond_.notify_one()` is faulty](https://github.com/googleapis/google-cloud-cpp-spanner/blob/48494ad7b83e31adcd0f778b75e8e33ad607ef66/google/cloud/spanner/internal/session_pool.cc#L169-L175), I was trying to be clever and ended up being too clever.

I ran under gdb and ^C'd when the deadlock happened, finding that there were threads blocked on `cond.wait()` in `SessionPool::Allocate()`, despite the fact `sessions_` had plenty of available sessions. I suspect the way this happens is:

consider 4 threads, and session_pool max size = 2 (assume min_size=2 as well, so the sessions are allocated up front, just to simplify because it's not related to the bug).

* T1: `Allocate()` - takes Session1 from pool
* T2: `Allocate()` - takes Session2 from pool
* T3: `Allocate()` - block (`cond_.wait()`) because `sessions_` is empty and we're at max size (2).
* T4: `Allocate()` - block, same as T3.
* T1: `Release()` - adds Session1 to pool; since `sessions_` was empty it calls `cond_.notify_one()`.

The call to `notify_one()` will cause either T3 or T4 to wake up, **but** there is no guarantee the notified thread (either T3 or T4) runs immediately - instead, T2 could run and call `Release()`.

Let's say T3 is the thread that gets notified.

* If T3 **does** wake up, reacquire the lock, and allocate a session a session then `sessions_` becomes empty again, so when T2 executes `Release()` it will properly `cond_.notify_one()` which wakes up wake up T4, and all is fine.
* However, if T2 `Release()` runs first, then it finds `sessions_` non-empty and thus does not call `cond_.notify_one()`. So, T4 never wakes up - even if T3 eventually calls `Release()`, `sessions_` is still non-empty so it doesn't notify T4.

A couple possible solutions:
* Unconditionally call `notify_one()`. I wanted to avoid this is because in my experience it's expensive even if there are no waiters, but I can benchmark it. [This](https://stackoverflow.com/questions/48936591/is-the-performance-of-notify-one-really-this-bad) kind of suggests it's worth avoiding. Note the usual case is there are zero waiters (your pool should be large enough to avoid it) so we don't have anyone to notify.
* Keep track of the number of threads waiting for a session. This is cheap, just a regular `int` since we're already holding the lock anywhere we access it.  And, it addresses a [TODO](https://github.com/googleapis/google-cloud-cpp-spanner/blob/48494ad7b83e31adcd0f778b75e8e33ad607ef66/google/cloud/spanner/internal/session_pool.cc#L121-L124) about determining how many sessions to create when the pool has to grow. So, I'm inclined to go with this option.
