### ISSUE TITLE
Consider how to represent debug info for classes.

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp-spanner#105]
Do we want to have a consistent mechanism for "stringifying" types for debug purposes?
Value currently uses void PrintTo(Value const&, std::ostream*) as it integrates nicely with gUnit.
Another option would be to overload ostream& operator<<(ostream&, Value const&).

What is the best way to indicate that these strings are for debugging purposes and not a machine interpretable serialization of the type?

**Comment by devjgm** [comment]
I believe the strategy used thus far has been:

- If a type has a logic, canonical string representation, implement it using `op<<()`. An example of this is the `Timestamp` type: https://github.com/googleapis/google-cloud-cpp-spanner/blob/24609cdd450f245c460bc125938aa8543f3d023f/google/cloud/spanner/timestamp.h#L109

- If the type does *not* have a canonical string format and we have no need to to support user-specified format specifiers for the type, we avoid `op<<()` to avoid users be confused or mislead by our choice of string format. In some of these cases, we may define a `PrintTo()` overload so that *our own* unit tests print a nice error message. `PrintTo()` is chosen instead of `op<<()` to make it clear that this is for unit tests only. An example of this is the `Value` class, which does not have canonical forms for printing vectors or structs: https://github.com/googleapis/google-cloud-cpp-spanner/blob/05a2e3ad3ee0ac96164013ce4d9cfce251059569/google/cloud/spanner/value.h#L306

This strategy doesn't seem bad to me. Is there something we should change about this? If not, maybe we should close this issue.

**Comment by devjgm** [comment]
We talked a bit about this offline. It sounds like the conclusion is to follow the strategy that I described in my previous comment for now. That should be fine for now. If we think of something better at some point, we can switch to that.
