### ISSUE TITLE
Automatically test quickstart/README.md instructions

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1293]
We should automatically test the instructions in the README.md file as part of the CI builds. Don't forget to test:

- [ ] macOS
- [ ] Windows
- [ ] Linux (more than 1 distro)

separately.

**Comment by devjgm** [comment]
UPDATE: The top-level README.md file no longer has these instructions. They are now in `quickstart/README.md`. But the request to test them still stands.

**Comment by devjgm** [comment]
This may be done, because:

1. We have google/cloud/.../quickstart/README.md files, which don't have instructions, they only have a code sample, which is compiled and tested.
2. Our quickstart directories do have CMake and bazel build files as an example for users, and these are also tested.
3. We have a general `doc/packaging.md` file now, with instructions that are also tested (I'm pretty sure).

So I think this can be closed?

**Comment by coryan** [comment]
I think we should close this.  Note that the checks and the instructions are written separately, and there is some brittleness there.  For example, we need to download the `roots.pem` file for Windows and macOS, and this is noted in the README files, and done in the build scripts.  If we ever need to download additional files, the scripts would fail, we wold detect that, fix it, but there is no automation to change the README when we do.
