### ISSUE TITLE
Enable angle-bracket includes in bazel

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1424]
It would be nice if bazel users could include our headers using angle-bracket includes, treating us like a system header. This way, they won't see any warnings/errors from our headers.

One way to do this is to edit the https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/BUILD file and add the bazel rule option of `includes = ["."]` to the build target (e.g., `//:spanner_client`). This works, however, it results in other odd behaviors, such as those described in https://github.com/googleapis/google-cloud-cpp-spanner/issues/1296#issuecomment-599759222

Therefore, we rolled back this change in https://github.com/googleapis/google-cloud-cpp-spanner/pull/1423

We should consider if there are other ways to support this. One idea is:

1. Move `google/` into a new top-level directory, like `src/`.
2. Update the top-level BUILD file rule for `//:spanner_client` to have
```py
includes = ["src"]
```

I *think* that might work, but it's untested.

**Comment by devjgm** [comment]
Note that bazel recommends against doing this. They recommend including using double-quotes not angle-brackets. See https://docs.bazel.build/versions/master/bazel-and-cpp.html#include-paths

**Comment by coryan** [comment]
On the one hand it is possible that only a few of us need to support angle brackets with Bazel. We want that because we compile with Bazel and CMake, with the dependencies (say `grpc`) compiled from source for Bazel, and with the dependencies "installed" for CMake (even super builds really install the deps).  So in the CMake case angle brackets is the best (`#include <grpcpp/grpcpp.h>`), and I do not want to change the code to compile with Bazel (to `#include "grpcpp/grpcpp.h"`).

It is possible (or likely) that our users (excluding libraries based on our libraries) would exclusively use Bazel or CMake.  So for them it is **perfectly fine** to use only one include style.

Just food for thought.

**Comment by devjgm** [comment]
In order to make this work, I think we may need a different directory structure for our source code so that bazel doesn't complain when we use the `includes` directive. That is being tracked in https://github.com/googleapis/google-cloud-cpp/issues/3719, which I think is a prerequisite for this issue. I've commented to that fact in that other issue. Closing this one.
