### ISSUE TITLE
SessionPool needs a way to inject a clock for testing

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1428]
In https://github.com/googleapis/google-cloud-cpp-spanner/pull/1425, @coryan said:

> > google/cloud/spanner/internal/session_pool_test.cc, line 389 at r1 (raw file):

> > // NOTE: This test runs in real time. SessionPool does not currently provide

> Maybe create a bug and leave a TODO(#...) here to change SessionPool? We could change it 
> (SessionPool) to be a template class, e.g.:
>
> `template <typename Clock = std::chrono::steady_clock> class SessionPool`
> as this class is in the internal namespace that would not break anything, and we only need to use 
> it with a weird clock in the tests.

Alternatively, we may not need to make the whole class a template to inject the clock, we may be able to simply inject a function that produces a "now", maybe something like `std::function<std::chrono::steady_clock::time_point()> now`

**Comment by mr-salty** [comment]
A 3rd option is what we do internally, inject a Clock class that by default uses `steady_clock` but can be faked. The issue with that is that I think it would also have to be a shared_ptr<> since `Sessions` might outlive the `SessionPool`.

One way around that would be to provide a function like `GetClock()` that usually returns the real clock, but there's a `SetClockForTesting()` call that overrides it. IDK how I feel about that either.

I guess `std::function` kind of sidesteps this issue - as long as we can ensure all the `Sessions` and `SessionPools` are gone by the time we destroy the source of `now`, and if not we can use a `shared_ptr` inside there.  So, I think I've probably convinced myself to go with that option, although I like option 3 better aesthetically.  thoughts?

**Comment by coryan** [comment]
You are suffering from analysis paralysis.  The exact mechanism (mockable class, `std::function<>`, template parameter, monkey patching the `.o` file. holding a magnet over the computer to change the bits on the fly [*]) matters less than having a working, testable, `SessionPool`.  Just use the `std::function<>` and move on to higher value problems.  SessionPool is in the `internal` namespace, you can change it later without many complications.

`[*]`: okay that one may be a bad idea :-)
