### ISSUE TITLE
Consider simplifying compile-time configuration.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#177]
The default values for the retry, backoff, and polling policies can be configured at compile time, and then the application developer can override them at run-time. Maybe that is too much, we will rarely use the compile-time configuration, and it is doubtful anybody else will.

Reconsider the decision in the DatabaseAdminClient before we implement the other clients.

**Comment by devjgm** [comment]
FTR, I think the compile-time configurations in question here are these:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/0f4392f002c59766080a628d532ac6dc09cf566f/google/cloud/spanner/database_admin_connection.cc#L27-L63

**Comment by devjgm** [comment]
Unless we know we need to support compile-time configurations like this, it seems easier not to. And since these configurations are in .cc files, they would only take effect if compiling *our* code from source.

So, I'm kinda inclined to remove these knobs.

If you are, would you like something like this (I only did one file): https://github.com/googleapis/google-cloud-cpp-spanner/compare/master...devjgm:simplify-chrono-defaults?expand=1, where that just inlines the default values into the functions that are named something like "DefaultFooPolicy"? If you like this, I can finish doing this to `instance_admin_connection.cc` too.

Or would you rather keep all the chrono default values declared as constexpr constants at file scope? I could do that too. Let me know if you have an opinion.

**Comment by coryan** [comment]
> Or would you rather keep all the chrono default values declared as constexpr constants at file scope? I could do that too. Let me know if you have an opinion.

No strong opinions, the proposed changes LGTM.
