### ISSUE TITLE
Create "external" project showing how to use Spanner lib with cmake and bazel

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#195]
Developers must be able to easily use Cloud Spanner C++ client in their C++ project. We will support both Bazel and CMake projects. Comment from @coryan 

> ...this suggests we need a sample or test that uses the google-cloud-cpp-spanner project.
> 
> - It could be part of the same repository, but that makes it hard to show that the sample is really using the project "as-if" it was completely separate
> - or it could be in a separate repository, but that makes hard to test for every change....
> 
> Seems like a mini-design doc would be nice.

**Comment by coryan** [comment]
For what is worth, @remyabel contributed an "external" CMake project in #197.

The project lives in `ci/test-readme`, it will be compiled by one of CI builds.

I think this means we just need to:

- [ ] Create Bazel files for the same project.
- [ ] Test the Bazel files as part of the CI builds (maybe separate builds, or just one, because why test it everywhere)?
- [ ] Update the landing page for Doxygen to describe how to integrate the project with CMake and Bazel.

**Comment by remyabel** [comment]
You mean `ci/test-install` not `ci/test-readme`?

**Comment by coryan** [comment]
Doh, yes, `ci/test-install`, fixed the comment.

**Comment by coryan** [comment]
I think this is done. There is the issue of running the test-install program as part of the CI, but we have two other issues open for it.
