### ISSUE TITLE
Create examples showing how to do error handling with StatusOr.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#245]
And link these examples from the reference doc landing page.

**Comment by devjgm** [comment]
So that I'm clear, where should these examples live? In client.h?

[status_or.h](https://github.com/googleapis/google-cloud-cpp-common/blob/master/google/cloud/status_or.h) already has example about this. Do you think it's good enough to link to that, or do you think Spanner needs something extra, or maybe specific to spanner?

**Comment by coryan** [comment]
I was thinking about the "Error Handling" section here:

https://googleapis.dev/cpp/google-cloud-storage/latest/

The equivalent section for the Spanner library is kind of bare:

https://googleapis.github.io/google-cloud-cpp-spanner/latest/
