### ISSUE TITLE
Add skeleton classes for spanner::Client and related types

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#26]
We should restructure the spanner sketch/skeleton code (`jgm.cc`) and check it into master as a base for future implementation work.
* Split it into multiple files (`client.h`, `transaction.h`, `value.h`, etc...)
* Add BUILD rules
* Use `google::cloud` `Status/StatusOr` and `Optional` types
* Make it build under C++11

(split out from #13)

**Comment by devjgm** [comment]
FYI, I filed separate issues for each of the "related types". We may want to handle each of these separately with separate issues so it shards easier. If so, we can probably close this issue, and you could take, say #29 if you want. Thoughts?

**Comment by devjgm** [comment]
Any thoughts on the previous comment? I think we may want to just close this issue since there are separate issues for each individual class. I suggest this because I think the sketch code (jgm.cc) was pretty rough and it'd take some work to make each class/type good enough even to be submitted as a skeleton.

Thoughts? I'll let @mr-salty close this issue if he agrees.

**Comment by devjgm** [comment]
Closing. See previous comments. Separate issues have been filed for each client, transaction, etc. skeleton.
