### ISSUE TITLE
Value::is() and !is_null() are not sufficient to ensure validity

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#312]
It's possible to construct a `Value` where `is()` returns `true` and `is_null()` returns `false` but `get()` will still return a non-OK status. It's not clear that this can happen from the documentation for `get()` or `operator T()`, so at minimum we should update the comments (although I think it effectively makes the latter impossible to use safely).

I did this using `FromProto` - it's possible that the "normal" constructors will never create this problem.  Specifically in this case, I created a value where the type was INT64 and the protobuf::Value was a number_value. This causes `Value::get()` to fail with {kUnknown, "missing INT64"} because the protobuf does not contain a string_value.

Perhaps `FromProto` needs to be able to return `StatusOr<Value>` to prevent this?  Or `is()` should take it into account?

**Comment by coryan** [comment]
IMO, as this may change the API it should be fixed before Alpha.

**Comment by devjgm** [comment]
`is()` and `is_null()` are not intended as a way to "validate" a `Value`. The only way to validate that a `Value` holds some actual, retrievable value is to extract it with `get()` (which returns `StatusOr`).

So perhaps the API is confusing on this point. Rather than changing the documentation, I think a better fix may be to simply remove `is()` from the API. I don't think it's needed, and I can't think of any case where a caller would want to call `is()` without calling `get()`.
