### ISSUE TITLE
docker cmake-super build compiles with -j1

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#342]
The docker cmake-super build takes significantly longer than other builds (2-3x).  From the logs we see:

`make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.`

@coryan suggests we could use ninja or CMAKE_BUILD_PARALLEL_LEVEL if we move to cmake-3.12+ https://github.com/googleapis/google-cloud-cpp/issues/2278

**Comment by mr-salty** [comment]
assigning to myself as interrupts oncall

**Comment by remyabel** [comment]
Note that since we probably can't upgrade to CMake 3.12+ this is the current approach taken:

https://github.com/googleapis/google-cloud-cpp/blob/master/cmake/ExternalProjectHelper.cmake#L127-L140

Then put `set_external_project_build_parallel_level(PARALLEL)` in every external project file.

Is `${PARALLEL}` actually defined anywhere in spanner?
