### ISSUE TITLE
Enable clang-tidy on our headers

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#355]
Apparently we are not enforcing the `kCamelCase` naming convention for them.

**Comment by remyabel** [comment]
The correct key is already there: `EnumConstantCase`. I think the actual issue is that clang-tidy is not being enforced for header files. We can either specify `HeaderFilterRegex` in `.clang-tidy` or somehow pass the header files via CMake.

**Comment by coryan** [comment]
Thanks, that explains why @mr-salty thought it was not working and I thought it was.  The errors in `.h` files were not showing up.

**Comment by devjgm** [comment]
We have `readability-identifier-naming` enabled, which seems to provide good value for us. We have it configured to check our naming of classes, structs, etc. Here's our config:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/762021bc1a7bb14eec0173e586e529e64adc7697/.clang-tidy#L26-L47

The problem is that this check also warns about our header include guards, which end with a trailing underscore, like `DIR_FOO_H_`. It doesn't like the trailing underscore. Note, setting `readability-identifier-naming.MacroDefinitionCase` to `aNy_CasE` does not fix the problem.

To fix this, I think we need to do one of:

* Disable all of `readability-identifier-naming`
* Change our header include guard style to look like `DIR_FOO_H`, i.e., remove the trailing underscore.

I don't know if there are other options. I'm leaning toward changing the include guard format.

**Comment by coryan** [comment]
For what it is worth, I vote for changing the include guards.  Can we also start the process to fix the style guide:

https://google.github.io/styleguide/cppguide.html#The__define_Guard

It irks me that our style guide is so non-enforceable.
