### ISSUE TITLE
Implement spanner::RunTransaction()

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp-spanner#357]
Implement the body and unit test for `spanner::RunTransaction()`.

The major part is the retry logic for aborted transactions.

**Comment by coryan** [comment]
For what is worth, I think I just saw a build fail due to an aborted transaction:


https://sponge.corp.google.com/target?id=3ae445f5-d4c2-4111-ab41-01927a8c5982&target=cloud-cpp%2Fspanner%2Fdocker%2Fintegration&searchFor=

The log is not great, but I believe the code that failed was:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/80fd25aa66e32860c76f0a8375f3d7c320f2b6ea/google/cloud/spanner/samples/samples.cc#L375-L386

**Comment by coryan** [comment]
@devbww  What exactly is missing from the implementation at this point?  Feels complete to me.

**Comment by devbww** [comment]
> What exactly is missing from the implementation at this point? Feels complete to me.

The issue was written before `RunTransaction()` had any retry for aborted `Commit()`s, so given that it has grown some I will close this.

Although I still believe `RunTransaction()` should only be looking at `ABORTED`.
