### ISSUE TITLE
Consider `Client::ExecuteSql()` overloads with `std::string`.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#389]
It is fairly common to write simple queries like: `client.ExecuteSql("SELECT a, b FROM tbl")`, currently all the overloads require a `SqlStatement` which means the application developer (specially folks just learning about the library) need to wrap strings.

I think we should be doing this for them, it makes it easier to teach about the library.

**Comment by devjgm** [comment]
One way to achieve the same end-result but with a different implementation would be to make `SqlStatement`'s [constructor that takes a `std::string`](https://github.com/googleapis/google-cloud-cpp-spanner/blob/37e15b2c7b67a8cea2a41217bd370dc5666f42ea/google/cloud/spanner/sql_statement.h#L68) not be explicit. That would enable `client.ExecuteSql("select foo from bar")`, as you mentioned without the need for further overloads in `Client`. It would also enable

```cc
SqlStatement sql = "select foo from bar";
```
and 

```cc
SqlStatement sql = ...
if (sql == "select foo from bar") {
  ...
}
```

I'm not sure we want all of those, but if we do, then that may push us toward the implicit c'tor. To be clear, I'm not arguing for this option. I'm not sure of my opinion here. But we should probably consider it and use it or reject it explicitly.

**Comment by devjgm** [comment]
oops. I wrote a comment, then I personally didn't agree with what I wrote so tried to delete it, but I accidentally clicked something like "close and comment", sigh. So re-opening.

**Comment by mr-salty** [comment]
This is at cross purposes with #400 (preventing using untrusted strings for queries) so I'm not in favor of adding these overloads.

**Comment by coryan** [comment]
Now that #400 is closed this is relevant again.  Do we want the overloads with `std::string`?  My vote is yes.

**Comment by devjgm** [comment]
I was initially in favor of this, because I also find the frequent use of `SqlStatement` in our tests a bit redundant and annoying. However, I'm not sure if real-user code will have this same issue. For example, if real user code commonly uses bound params, they'll have to use `SqlStatement` anyway. 

I also looked at the tutorials for the other languages (https://cloud.google.com/spanner/docs/tutorials) and it looks like they all (?) require the SQL string to be part of some bigger "Statement" structure, such as Java's `Statement.of("select foo")`, or C#'s `connection.CreateSelectCommand("SELECT foo")`, or Node's `{sql: 'SELECT foo'}`.

I'm also slightly concerned that allowing bare strings to `ExecuteSql` may discourage users from using `SqlStatement` when they should be (such as using bound params instead of string manipulations on the main sql string), though maybe this concern is unfounded. 

If we do nothing now and continue to require users to type `SqlStatement("select foo")` for now, we can always add the `std::string` overload later if we have real user reports that it's a problem. But if we add this "convenience" now, we can never remove it (without major pain) if we learn it was unneeded or problematic.

Therefore, since it's not a *clear* win today in my opinion, I'd vote to skip this overload until we are slightly more sure that it's worthwhile.

My 2 cents.

**Comment by coryan** [comment]
Closing, I think we agree that we should not implement this.
