### ISSUE TITLE
protect against SQL injection attacks

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#400]
`SqlStatement` can be constructed from a std::string of arbitrary origin, which allows the possibility for SQL injection attacks, especially if any part of the query string is dependent on user input. We should prevent unsafe use of this API to the largest possible extent.

Ideally we should be only accept query strings from a trusted sources like string literals, with all untrusted values relegated to parameters as described in https://cloud.google.com/spanner/docs/sql-best-practices

**Comment by remyabel** [comment]
It is my understanding that SQL injection attacks are from the user to the application, not the application to the library. For example, an application that doesn't use parametrized queries is vulnerable to SQL injection. The library needs to trust input from the application (otherwise it wouldn't be very usable), but the application shouldn't trust input from the user as you should always assume the user is malicious.

> Ideally we should be only accept query strings from a trusted sources like string literals

Do you mean only allow string literals and not `std::string` or force the usage of only parametrized queries? I don't think either option would make the library very usable and the onus still falls upon the developer to minimize passing untrusted input to the library.

**Comment by mr-salty** [comment]
Correct - the idea is to make it difficult for the application developer to inadvertently pass untrusted input to the API. This does place some additional requirements on developers using the library, but the general feeling (inside Google, at least - this topic came up in an internal discussion) is that providing APIs that cannot be used unsafely is the best way to prevent these types of issues, and it's standard practice for a lot of APIs internally.

https://github.com/google/safe-html-types/blob/master/doc/safehtml-types.md is one example that's analogous to what I'm describing.

**Comment by remyabel** [comment]
That makes sense and thanks for the example. The `FromConstant` function is very interesting.

**Comment by devjgm** [comment]
FTR, one incomplete way to do this in C++ is with a class like this (https://godbolt.org/z/xr1aUx):

```cc
struct StringLiteral {
  template <std::size_t N>
  explicit StringLiteral(char const (&a)[N]) : s(a, N) {}
  std::string s;
};
...
StringLiteral s("hello");
```

It's incomplete because it only requires a constant character array, not specifically a string literal. Though incomplete, it's portable, and may still be useful or helpful in our library.

Additionally, there are some compiler extensions that would enforce compile-time string literals for us. The problem here is that portability may suffer. But we could look into this.

Also, there might be some way to build a compile-time string class out of something like

```cc
template <char ...>
struct StringLiteral { ... };
```

But this is just a guess and someone would need to work out the details (if it's possible).

**Comment by remyabel** [comment]
There is a proposal for something similar: [n4121 std::string_literal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4121.pdf)

It's from 2014 but there may be a newer or more modern incarnation of the same concept. Or if it doesn't exist, we can just implement it.

**Comment by devjgm** [comment]
What do we think about something like this: https://github.com/googleapis/google-cloud-cpp-spanner/pull/407

As a follow-up PR, we could add some compiler-specific extension hooks to ensure even more that the arguments are compile-time strings.

It's not a 100% solution, but it encourages safe practices, and makes unsafe practices harder and fairly explicit.

**Comment by remyabel** [comment]
Personally, I still vote for implementing the `basic_string_literal` class (or some other incarnation of it).

Pros:

- No need for compiler-specific extension hooks
- We have a self-documenting strong type
- We can simply pass a `string_literal` around, rather than having `char const (&arr)[N]`

Cons:

- Additional complexity
- More code to maintain

Furthermore, if we are following the example of the `SafeHtml` library I like the idea of being explicit. So the analogue of `FromConstant("this-enforces-the-string-to-be-a-compile-time-string")` to something like `SqlStatement sql1(string_literal{"select ...."});`

There may be specific design disadvantages that I haven't thought of. Thoughts?

**Comment by devjgm** [comment]
@remyabel so that I'm clear, are you suggesting a particular difference in implementation, or are you simply proposing that whatever we do here should be done more generically and named something like "StringLiteral" (or `google::cloud::basic_string_literal` or something)?

**Comment by remyabel** [comment]
I believe your current implementation (which could be perfectly fine) accepts non-const char arrays. For example:

```C++
struct Foo {
    template <std::size_t N>
    Foo(char const (&arr)[N]) {
        static_assert(N > 0, "String literal required");
    }
};

Foo foo("test");
char c[5] = "test";
Foo foo2(c); // allowed
```

Using `std::basic_string_literal`:

```C++
struct Bar {
    template <std::size_t N>
    Bar(std::basic_string_literal<char, N> wah) {
    }
};

Bar bar(wah);
Bar bar2(c); // compiler error
```

[Live example](https://gcc.godbolt.org/z/occKEM)

**Comment by devjgm** [comment]
The `basic_string_literal` example you posted also accepts non-const char arrays. See https://gcc.godbolt.org/z/6ftlVA

```cc
  char c[5] = "test";
  std::basic_string_literal<char, 5> wah = c;  // <-- compiles
```

That solution makes it look prettier in general though because it's using C++17 class-template argument deduction. Sadly, this library needs to support a lot of users, and most users are still using C++11, so we're stuck there.

The general mechanism used by `basic_string_literal` is exactly the same as the one used in PR #407. They both use a function template with a non-type template parameter to detect an array size.

**Comment by remyabel** [comment]
> The basic_string_literal example you posted also accepts non-const char arrays. See https://gcc.godbolt.org/z/6ftlVA

Good point. I missed that the compiler error for my example was for a completely different reason.

> That solution makes it look prettier in general though because it's using C++17 class-template argument deduction. Sadly, this library needs to support a lot of users, and most users are still using C++11, so we're stuck there.

That's a progressive enhancement and controlled by the `#ifdef`. Naturally the proposal includes it in the example implementation, but we don't need it.

**Comment by devjgm** [comment]
So it sounds like the real question for us to decide is should we give `SqlStatement` this constructibe-from-a-string-literal support directly, or should we factor it out into a separate `StringLiteral` class.

Some questions/comments to answer this:

1. Do we need this support anywhere else? I can't think of anywhere else we need it.

2. If we bake this support into `SqlStatement` (as #407 does), maybe we can consider making its constructor non-explicit, which seems pretty safe since it can only be implicitly constructed from string literals. The benefit of doing this is that then syntax like `client.ExecuteSql("SELECT Foo from Bar")` will automatically work (which we wanted int #395).

**Comment by remyabel** [comment]
> Do we need this support anywhere else? I can't think of anywhere else we need it.

Feel free to abandon the idea since I had a misunderstanding of how it would solve the problem.

Here's another question. Presumably we only accept string literals because they are compile-time constants. Would it be acceptable to disallow non-const char arrays like `char disallowed[5]` but allow `const char allowed[5]`? Example:

```c++
struct SqlStatement {
  template <std::size_t N>
  SqlStatement(char (&arr)[N]) = delete;

  template <std::size_t N>
  explicit SqlStatement(char const (&arr)[N])
      : statement_(arr, N - 1) {
    static_assert(N > 0, "String literal required");
  }

  std::string statement_;
};

int main() {
    SqlStatement s("hello");
    char disallowed[5] = "Test";
    // SqlStatement s2(disallowed);
    const char allowed[5] = "Test";
    SqlStatement s3(allowed);
    const char *disallowed2 = "test";
    // SqlStatement s4(disallowed2);
}
```

**Comment by coryan** [comment]
> So it sounds like the real question for us to decide is should we give `SqlStatement` this constructibe-from-a-string-literal support directly, or should we factor it out into a separate `StringLiteral` class.

Yes.

> 
> Some questions/comments to answer this:
> 
> 1. Do we need this support anywhere else? I can't think of anywhere else we need it.

I think we will need this for BigQuery when/if we implement that library?

There is also this crazy expression language that is used in several services and (maybe, I am not really sure) could benefit from this:

https://github.com/google/cel-spec

**Comment by devjgm** [comment]
The decision from Spanner product folks is that the C++ library should behave like the other Cloud Spanner libraries in other languages in this regard, meaning that we should *not require* or go out of our way to support SQL-hardening techniques. We *should* support SQL queries from runtime-computed sql query strings, and not require SQL query strings from compile-time literals, etc.

Note, since we support bound parameters, that helps a bit to protect against SQL injection attacks since user-supplied parameters should be specified as a bound param, and not as part of the generated SQL query string itself.

So, at this point, there is nothing for us to do. At some point if we have an actual feature request to support SQL-injection mitigation, we can open a new issue for that request.
