### ISSUE TITLE
write design doc for Spanner retries

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#504]
Certain spanner operations need to be retried. We may need to retry due to idempotent network issues, failed RW transaction commits, etc. We may need to support retying at different levels. This is all complicated enough that we probably need a short design doc proposing how retries should work.

**Comment by devjgm** [comment]
Note: This may also be related to #271

**Comment by coryan** [comment]
Some general thoughts on this topic, for consideration when writing the design doc:

Some operations in spanner are simple idempotent RPCs by definition, for example `GetDatabase` or `GetInstance` are simple reads, they return a single value, they either succeed or fail. Those can be safely retried for transient failures.

That suggests one should define what failures are transient, for that, this is a good start: https://grpc.github.io/grpc/cpp/md_doc_statuscodes.html

Some operations in Spanner are idempotent even though they are write operations, for example, a `Commit()` for a transaction with an `id()` would only succeed once.  That suggests such operations *are* retryable on transient failures.

Some operations in Spanner like `GetOperation()` RPCs can be allowed to fail without retrying because they execute as part of polling loop. There is an implicit retry for them.  Do we want to avoid retries for operations inside a `RunTransaction()/RunCommitBlock()`?

In other services operations are idempotent depending on their parameters (e.g., a "create if does not exist" operation is idempotent in GCS, while "create new version" is not).  Do we have such operations in Spanner?

Some operations in Spanner (`Read()` and `ExecuteSql()`) can be *resumed* on a partial failure, that is the issue raised in #271.

One question is whether something like `ExecuteBatchDml()` is retryable on a partial failure.  Should the remaining (not applied) statements be executed a second time?



In addition to the question of *what* gets to be retried one should determine *how*?  What class is responsible for retrying?  For how long?  Do we backoff?  And are these p

**Comment by coryan** [comment]
I am going to call this done.
