### ISSUE TITLE
Fix build metadata for the spanner library.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#81]
The library is picking up build metadata, such as the git revision, compiler version, and compiler flags, from the build for `google_cloud_cpp_common`. That is misleading, we should use the build information for the library itself.

**Comment by devjgm** [comment]
I looked into this a bit so that I could understand it better. Here are some of my notes to remind myself later or maybe to help someone else.

The build metadata is compiled into the `google_cloud_cpp_common` library from this file: https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/internal/build_info.cc.in. That ".in" file is converted to a .cc file by cmake and/or bazel. The .cc file (and a .h) file is compiled into the library.

That "build_info.h" interface is used by both the [cloud bigtable code](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/metadata_update_policy.cc#L42) and the [gcs code](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/version.cc#L41).

I agree with the OP on this issue that we probably want to have separate build metadata for the spanner library. Furthermore, I think we probably want to have a separate build_info for bigtable and gcs too.

So...

So I think we might want *each* individual library (gcs, bigtable, spanner, etc) to use and compile their *own* build_info.cc file. Each one would be in the product's own namespace, so there's no naming conflicts. This would allow the build metadata to work and report accurately for any of our libraries regardless of which ones are linked into a binary.

Thoughts?

If this sounds reasonable, I think the steps would look like

1. Split the build_info.cc files that are in the `google_cloud_cpp_common` library into separate files that are namespaced for bigtable and gcs. This should probably have an issue in that project.

2. Create a new build_info.cc file, build rule, etc. for spanner in the spanner namespace. We can use that one for spanner's stats reporting.

**Comment by devjgm** [comment]
Actually, I think those steps are independent of one another. I think it would be fine to do step 2 before 1. That is, I think we can create Spanner's `build_info.{h,cc}` files while the ones in `google_cloud_cpp_common` continue to exist where they are. We just need to make sure that the symbols we generate are in each product's namespace.
